-- Seed: CMS detail blocks with existing copy and placeholder images (distinct from hero grid)
-- Note: Image URLs are placeholders and intentionally different from hero grid

TRUNCATE public.cms_detail_blocks RESTART IDENTITY CASCADE;

-- Helper to insert detail blocks
INSERT INTO public.cms_detail_blocks
    (page_slug, item_slug, title, paragraphs, image_url, alt_text, status, position)
VALUES
-- About
('about', 'event', 'Premium event experiences',
 '["JUARA Events menghadirkan pengalaman acara premium yang tak terlupakan. Kami menggabungkan kreativitas, teknologi, dan eksekusi sempurna untuk menciptakan momen yang berkesan bagi audiences Anda.",
   \"Dengan pendekatan 'off the grid' yang signature, kami menciptakan event-event unik di lokasi-lokasi tak terduga yang menantang batasan konvensional. Setiap konsep dirancang khusus untuk memberikan pengalaman immersive yang tidak hanya menghibur, tetapi juga bermakna dan transformatif.\",
   \"Tim kami berpengalaman dalam mengelola event skala besar hingga intimate, dari konser musik hingga corporate gathering, dari festival komunitas hingga launch produk eksklusif. Kami percaya bahwa setiap event adalah kesempatan untuk menciptakan kenangan yang akan dikenang selamanya.\",
   \"Dengan teknologi terdepan dan jaringan mitra yang kuat, JUARA Events memastikan setiap detail executes flawlessly. Dari perencanaan konsep hingga evaluasi pasca-event, kami hadir sebagai partner strategis yang memahami visi Anda dan berkomitmen mencapai hasil yang超越 ekspektasi.\"]'::jsonb,
 'https://dummyimage.com/800x600/0f172a/ffffff&text=Detail+Event', 'Detail Event', 'published', 1),
('about', 'community', 'Community-driven innovation',
 '["Kami percaya pada kekuatan komunitas untuk mendorong inovasi. JUARA Community mengubah kreator, profesional, dan visioner untuk berkolaborasi dan saling menginspirasi dalam ekosistem yang saling mendukung.",
   "Platform komunitas kami menyediakan ruang bagi para innovator untuk berbagi ide, membangun koneksi, dan mengembangkan proyek-proyek ambisius. Melalui workshop, meetup, dan program mentorship, kami memfasilitasi knowledge transfer dan skill development yang berkelanjutan.",
   "JUARA Community juga berperan sebagai bridge between industries, menghubungkan individu-individu talented dengan opportunity yang tepat. Kami memahami bahwa innovation terbaik lahir dari keberagaman perspektif dan kolaborasi lintas disiplin.",
   "Dengan berbagai inisiatif seperti creative labs, startup incubators, dan innovation challenges, kami terus mendorong boundaries dari apa yang возможно. Community kami bukan hanya tentang networking, tetapi tentang membangun masa depan yang lebih baik melalui collective intelligence."]'::jsonb,
 'https://dummyimage.com/800x600/111827/ffffff&text=Detail+Community', 'Detail Community', 'published', 2),
('about', 'tech', 'Next-generation experiences',
 '["Teknologi adalah jantung dari apa yang kami lakukan. JUARA Tech menghadirkan solusi inovatif yang mengubah visi menjadi kenyataan dengan kepercayaan diri, mengintegrasikan cutting-edge technology untuk menciptakan experiences yang truly revolutionary.",
   "Tim tech kami mengkhususkan diri dalam developing custom solutions yang mengoptimize setiap aspek event management. Dari AI-powered audience analytics hingga blockchain-based ticketing systems, kami leverage teknologi terdepan untuk streamline operations dan enhance participant experience.",
   "Inovasi kami tidak berhenti di event execution. Kami mengembangkan platform proprietary yang mengintegrasikan smart contracts, IoT sensors, AR/VR experiences, dan predictive analytics untuk menciptakan ecosystem yang fully connected dan data-driven.",
   "Dengan pendekatan agile development dan continuous innovation, JUARA Tech memastikan bahwa clients selalu stay ahead of the curve. Kami tidak hanya follow trends, tetapi menciptakan teknologi baru yang mendefinisikan future dari event industry."]'::jsonb,
 'https://dummyimage.com/800x600/0b1220/ffffff&text=Detail+Tech', 'Detail Tech', 'published', 3),
('about', 'analytic', 'Data-driven insights',
 '["Data memberikan pemahaman mendalam. JUARA Analytics menggunakan insights berbasis data untuk mengoptimalkan strategi dan memaksimalkan ROI dari setiap kampanye, memberikan competitive advantage yang measurable dan actionable.",
   "Platform analytics kami mengumpulkan dan menganalisis data real-time dari berbagai touchpoints: social media engagement, audience behavior, sentiment analysis, hingga conversion metrics. Visual dashboards yang intuitive membantu stakeholders make informed decisions berdasarkan evidence.",
   "Dengan advanced machine learning algorithms, kami dapat memprediksi trends, mengidentifikasi patterns yang tidak obvious, dan memberikan recommendations yang personalized. Analytics kami tidak hanya report what happened, tetapi explain why it happened dan predict what will happen next.",
   "ROI measurement adalah core dari everything yang kami lakukan. JUARA Analytics membantu clients understand true impact dari setiap event, dari brand awareness metrics hingga revenue attribution, dari audience retention rates hingga lifetime value calculations."]'::jsonb,
 'https://dummyimage.com/800x600/121b2e/ffffff&text=Detail+Analytics', 'Detail Analytics', 'published', 4),

-- Product
('product', 'audience-flow-management', 'Seamless Audience Journey',
 '["Kami mendesain journey audiens end-to-end: dari pre-event onboarding, akses lokasi, hingga egress, supaya alur terasa mulus dan terukur.",
   "Crowd control dengan zoning, queue orchestration, dan wayfinding yang jelas untuk mencegah bottleneck dan menjaga safety.",
   "Integrasi smart access system (RFID/NFC, biometric) dan real-time monitoring untuk tracking arus pergerakan dan optimasi on the fly.",
   "Pendekatan berbasis data dan psikologi audiens: memanfaatkan FOMO, social proof, dan loss aversion agar engagement naik tanpa friksi."]'::jsonb,
 'https://dummyimage.com/800x600/1f2937/ffffff&text=Detail+Audience+Flow', 'Detail Audience Flow', 'published', 1),
('product', 'creative-agency', 'Creative Agency',
 '["Kami menggabungkan kreativitas dan data untuk membangun konsep yang relevan, bernilai jual, dan beda di industri event.",
   "Storytelling multisensori: visual, audio, interaksi, dan ritme dramaturgi dirangkai agar pesan brand terasa hidup.",
   "Process yang rapi dari brief → concept → prototype → playbook eksekusi, dengan guardrail feasibility dan ROI.",
   "Kolaborasi lintas disiplin (design, tech, production) memastikan ide bukan hanya indah di deck, tapi matang di lapangan."]'::jsonb,
 'https://dummyimage.com/800x600/0f172a/ffffff&text=Detail+Creative+Agency', 'Detail Creative Agency', 'published', 2),
('product', 'event-activation', 'Event Activation',
 '["Mengubah pesan brand menjadi pengalaman interaktif yang menciptakan percakapan luas dan memori kolektif.",
   "Brand storytelling dipadu teknologi interaktif (AR, RFID, IoT, gamification) untuk engagement yang terasa natural.",
   "Design activation mengutamakan flow, dwell time, dan conversion metric yang jelas; bukan sekadar instalasi cantik.",
   "Tim produksi memastikan setup, operasi, hingga post-event reporting berjalan clean dan accountable."]'::jsonb,
 'https://dummyimage.com/800x600/0e1524/ffffff&text=Detail+Event+Activation', 'Detail Event Activation', 'published', 3),
('product', 'mice-event', 'MICE Event',
 '["Mendefinisikan ulang MICE: meeting, incentive, conference, exhibition dengan pendekatan dinamis dan audience-centric.",
   "Optimasi networking, content delivery, dan partisipasi audiens melalui format yang engaging dan terukur.",
   "Integrasi sistem digital: registrasi, ticketing, tracking, hingga live analytics untuk keputusan real-time.",
   "Outcome-oriented: KPI, ROI, dan rekomendasi pasca event untuk siklus perbaikan berkelanjutan."]'::jsonb,
 'https://dummyimage.com/800x600/111827/ffffff&text=Detail+MICE', 'Detail MICE Event', 'published', 4),
('product', 'music-concert-management', 'Music Concert Management',
 '["Kami merancang dan mengeksekusi konser musik dengan energi tinggi, menggabungkan ritme, crowd dynamics, dan momentum panggung menjadi satu narasi yang kohesif.",
   "Sound engineering, stage design modular, dan sistem visual (lighting, projection, screen) dikurasi agar setiap lagu terasa seperti bab dalam sebuah cerita yang imersif.",
   "Operasional di belakang panggung—dari talent routing, jadwal soundcheck, hingga koordinasi kru—diatur dengan presisi supaya artis dan penonton sama-sama mendapatkan pengalaman terbaik.",
   "Setelah acara, kami melakukan analisis data dan dokumentasi untuk mengukur dampak brand, engagement audiens, dan menyusun rekomendasi perbaikan konser berikutnya."]'::jsonb,
 'https://dummyimage.com/800x600/0b1220/ffffff&text=Detail+Music', 'Detail Music Concert', 'published', 5),
('product', 'sport-event-management', 'Sport Event Management',
 '["Kami mengelola event olahraga dari sisi operasional dan experience: mengatur alur atlet, official, dan penonton agar pertandingan terasa tertib namun tetap penuh adrenalin.",
   "Desain venue, tribun, dan area aktivasi disusun untuk memaksimalkan visibilitas, keselamatan, dan atmosfer kompetisi—baik untuk pertandingan indoor maupun outdoor.",
   "Koordinasi lintas-stakeholder (federasi, sponsor, broadcaster, dan pihak keamanan) dijalankan dengan SOP yang jelas supaya event berjalan sesuai regulasi dan standar profesional.",
   "Kami juga menyiapkan framework evaluasi pasca event: metrik attendance, engagement, media value, serta rekomendasi untuk meningkatkan kualitas sport event di edisi berikutnya."]'::jsonb,
 'https://dummyimage.com/800x600/0f172a/ffffff&text=Detail+Sport', 'Detail Sport Event', 'published', 6),

-- Services
('services', 'creative-and-plan-development', 'Creative & Plan Development',
 '["Kami merancang strategi acara berbasis data dan insight audiens untuk memastikan konsep tepat sasaran dan berdaya jual.",
   "Blueprint menyeluruh dari tujuan bisnis → narasi → pengalaman multisensori, disertai playbook eksekusi yang terukur.",
   "Prototyping cepat untuk menguji feasibility, risk, dan impact sebelum naik produksi, menjaga efisiensi biaya dan waktu.",
   "Kolaborasi erat dengan stakeholder untuk menyatukan creative vision dan operational constraints agar hasil konsisten dan terukur."]'::jsonb,
 'https://dummyimage.com/800x600/1f2937/ffffff&text=Detail+Creative+Plan', 'Detail Creative Plan', 'published', 1),
('services', 'execution-handling', 'Execution Handling',
 '["Eksekusi presisi tinggi dengan koordinasi lintas-stakeholder, memastikan setiap detail berjalan sesuai rencana.",
   "Run of show yang jelas, risk mitigation, dan SOP operasional menjaga kualitas, keamanan, dan ketepatan waktu.",
   "Team onsite yang agile untuk resolving issues secara real-time, mengurangi downtime dan menjaga pengalaman audiens.",
   "Post-event wrap dengan dokumentasi dan evaluasi menyeluruh sebagai dasar perbaikan berkelanjutan."]'::jsonb,
 'https://dummyimage.com/800x600/0e1524/ffffff&text=Detail+Execution', 'Detail Execution', 'published', 2),
('services', 'talent-and-logistic-management', 'Talent & Logistic Management',
 '["Kurasi talent yang tepat dan manajemen logistik end-to-end untuk mendukung eksekusi tanpa hambatan.",
   "Routing, transportasi, akomodasi, dan distribusi diatur presisi agar operasional efisien dan tim fokus pada kualitas acara.",
   "Koordinasi dengan vendors dan partner memastikan SLA terpenuhi dan resiko operasional terkelola.",
   "Pelaporan pasca event mencakup penggunaan resource, efisiensi biaya, dan rekomendasi untuk optimasi berikutnya."]'::jsonb,
 'https://dummyimage.com/800x600/0b1220/ffffff&text=Detail+Talent', 'Detail Talent Logistic', 'published', 3),
('services', 'local-authority-liaison', 'Local Authority Liaison',
 '["Pengurusan perizinan, regulasi, dan koordinasi dengan otoritas setempat untuk memastikan acara berjalan lancar dan patuh aturan.",
   "Risk assessment dan compliance checklist disiapkan sejak awal untuk menghindari hambatan operasional.",
   "Hubungan yang baik dengan pihak berwenang mempercepat proses, meningkatkan safety, dan kepercayaan publik.",
   "Dokumentasi lengkap dan pelaporan transparan menjadi fondasi governance yang kuat untuk setiap event."]'::jsonb,
 'https://dummyimage.com/800x600/111827/ffffff&text=Detail+Authority', 'Detail Authority Liaison', 'published', 4);
